### ISSUE TITLE
target/generated-test-sources not added as source folder

### ISSUE THREAD

**Issue by jfbenckhuijsen** [jbosstools/m2e-apt#36]
Hi,

I've configured a project using m2e-apt. Annotation sources generated from classes in src/main/java are added to the Eclipse project as a new source folder target/generated-sources/annotations. However, for classes processed from src/test/java, no such source folder (target/generated-test-sources/annotations) is added to the Eclipse project. A maven build correctly outputs these classes.

**Comment by fbricon** [comment]
JDT APT (the Eclipse tooling) doesn't support multiple annotation processing build sources/outputs (https://bugs.eclipse.org/376848). 

https://developer.jboss.org/en/tools/blog/2012/05/20/annotation-processing-support-in-m2e-or-m2e-apt-100-is-out explains how to cope with that. Basically, you need to use the maven-processor-plugin and tell m2e-apt to delegate AP to it

**Comment by galan** [comment]
Regarding to https://bugs.eclipse.org/bugs/show_bug.cgi?id=531072#c13 it should be fixed in Eclipse Photon (4.8)
