### ISSUE TITLE
Resolve workspace projects

### ISSUE THREAD

**Issue by DenSpirit** [jbosstools/m2e-apt#38]
When a maven project containing annotation processors is imported into workspace, it doesn't show up in the list of annotation processors added by m2e-apt.

**Comment by fbricon** [comment]
This is a known limitation from Eclipse APT. See issue #15

This can't be fixed in m2e-apt. Sorry.

**Comment by DenSpirit** [comment]
Thanks for a fast response.
According to issue #15 "Annotation Processors from workspace projects are ignored.". What about accessing their target JAR files?

**Comment by fbricon** [comment]
Disabling workspace resolution on a project consuming APs from another project would make it use the jar installed in the local repository.
We can't rely on jars in target/ as there's no guarantee they'll be present. Any clean build would likely break stuff apart.
