### ISSUE TITLE
Types based on test sources should get generated to target/generated-test-sources/test-annotations

### ISSUE THREAD

**Issue by overheadhunter** [jbosstools/m2e-apt#46]
If you have annotated types inside `src/test/java`, the corresponding sources generated by the annotation processor during a normal maven build are put inside `target/generated-test-sources/test-annotations`. 

However the m2e-apt plugin puts them inside `target/generated-sources/annotations`, which leads to errors as the generated types now exist in both directories.

**Comment by fbricon** [comment]
This is a known issue described in https://github.com/jbosstools/m2e-apt/blob/master/README.md.
We can't do anything as this is a limitation from the Eclipse JDT APT plugin itself, which only supports 1 output directory. You can try the "delegate annotation processing" strategy.

**Comment by totalvoidness** [comment]
@fbricon Are you aware of any upstream bug report? Modifying the maven build just to make an IDE happy isn't exactly a solution, that makes me happy :wink: Anyway feel free to close this issue if there is nothing you can do about it

**Comment by fbricon** [comment]
I opened https://bugs.eclipse.org/376848 a while ago

**Comment by fbricon** [comment]
Fixed with #63. Will work in Eclipse Photon
