### ISSUE TITLE
Annotation processor configuration fails when maven-compiler-plugin is configured with a non-JAR dependency

### ISSUE THREAD

**Issue by atomicknight** [jbosstools/m2e-apt#52]
`AbstractAptConfiguratorDelegate` assumes that all dependencies of maven-compiler-plugin are JAR files; this is true except when dependencies have been added to the plugin classpath. When this occurs, the plugin silently fails to configure the annotation processors because it is unable to read the dependency as a JAR file.

The offending piece of code is here: https://github.com/jbosstools/m2e-apt/blob/master/org.jboss.tools.maven.apt.core/src/org/jboss/tools/maven/apt/internal/AbstractAptConfiguratorDelegate.java#L128

Here is a test case illustrating the issue: https://github.com/atomicknight/m2e-apt-testcases/tree/master/nonjar_plugin_deps. Even though the project has an annotation processor on the compile classpath (Hibernate JPA metamodel generator), the processor is not configured because the non-JAR plugin dependency is tested first, causing an exception to be thrown before the Hibernate JAR is tested.

**Comment by fbricon** [comment]
How is a pom dependency supposed to work?

**Comment by atomicknight** [comment]
The POM dependency itself doesn't contribute any classes/resources. However, it does cause transitive dependencies to be pulled in.

In my actual project, the POM dependency is not declared directly but is instead a (transitive) dependency of a declared JAR dependency.

**Comment by fbricon** [comment]
@atomicknight a CI build is available from http://download.jboss.org/jbosstools/builds/staging/m2e-apt/all/repo/. Please let me know if it fixes your issue...or not.

**Comment by atomicknight** [comment]
@fbricon, the fix works great. Thanks!
