### ISSUE TITLE
Annotation processing is not enabled by default for JDT compiler

### ISSUE THREAD

**Issue by michaldo** [jbosstools/m2e-apt#53]
When I import Maven project with default compiler annotation processing is enabled, but for JDT compiler it is not enabled.

Steps to reproduce: Import project https://github.com/michaldo/m2e-apt-problem
### Environment: 

Eclipse Mars 4.5.2
Maven Integration for Eclipse JDT APT	1.2.0.201601252104
Window>Preferences>Maven>Annotation Processing>Automaticaly configure JDT...

Maybe it is already reported as #22 but those issue is quite old

**Comment by fbricon** [comment]
Please check if the latest build from http://download.jboss.org/jbosstools/builds/staging/m2e-apt/all/repo/ works for you

**Comment by michaldo** [comment]
Fixed
