### ISSUE TITLE
Question: Could pom.xml force Eclipse to enable APT processing?

### ISSUE THREAD

**Issue by michaldo** [jbosstools/m2e-apt#55]
If my project use annotation processor, Eclipse must have enabled APT processing to import project without errors.

- I may do it on workspace level by: Window>Preferences>Maven>Annotation Processing>Automaticaly configure JDT...
Drawbacks:
I have to do manual configuration every new Eclipse installation -> it is annoying
Workspace settings impacts all projects -> I prefer project isolation

- I may do it on project level
Drawbacks:
Annoying
I can't import project without error -> I have to import and then configure

- I may do it on project level and commit and commit `.settings/org.eclipse.jdt.apt.core.prefs`
Drawbacks:
I have to repeat it for each module in multi-module project
I have to commit properties which I don't want to manage, for example `org.eclipse.jdt.apt.genSrcDir`

Ideally, I could configure somewhere in my pom.xml that: "This project needs to work annotation proccessing enabled. When imported to Eclipse, turn on APT"

Is it possible?

**Comment by fbricon** [comment]
Yes, add a  an `<m2e.apt.activation>` Maven property to your (parent) pom.xml. See https://github.com/jbosstools/m2e-apt/issues/26#issue-26292488

**Comment by michaldo** [comment]
Works perfect. Thanks
