### ISSUE TITLE
annotationProcessorPaths alone does not enable annotation processing

### ISSUE THREAD

**Issue by Frettman** [jbosstools/m2e-apt#57]
I recently discovered _annotationProcessorPaths_ of the maven-compiler-plugin, which finally lets me get rid of **provided** or **optional** dependencies to annotation processors. The Maven build itself runs just fine, but annotation processing in Eclipse gets actively disabled for the project when I do an Alt+F5 and **target\generated-sources\annotations** is removed as source folder. According to #47 m2e-apt should support _annotationProcessorPaths_. I have 1.3.0.201610261805 which as far as I know includes this feature, right?
I attached a short pom.xml that demonstrates the issue:
[pom.xml.txt](https://github.com/jbosstools/m2e-apt/files/1145762/pom.xml.txt)

One observation I have made: Sometimes when updating the Maven project (Alt+F5), the **target\generated-sources\annotations** folder is added as a source folder for a split second and then disappears again.

Is this an issue with m2e-apt or am I just doing it wrong? Thanks in advance for any help.

**Comment by fbricon** [comment]
Can you please provide a complete project reproducing this issue?

**Comment by Frettman** [comment]
Here you are:
[test.zip](https://github.com/jbosstools/m2e-apt/files/1147356/test.zip)

Annotation processing is configured and activated in the Eclipse project when the _dependency_ is commented in; deactivated otherwise. For the Maven build itself the _annotationProcessorPaths_ configuration is enough; but m2e-apt doesn't seem to pick it up.

**Comment by Frettman** [comment]
Just an update on my ongoing research of this:
I found your test project for this feature:
m2e-apt/org.jboss.tools.maven.apt.tests/projects/p11/
It shows the same issue. So, assuming it's not a regression in the plug-in, I was starting to suspect an issue on my end. I tried a clean install of our preconfigured IDE (using Eclipse Oomph, includes Spring STS plugins) and a new workspace: same issue. Then I was trying a vanilla **Eclipse IDE for Java Developers** straight from eclipse.org: it works...
Clean installation of Spring STS: same issue.
So it seems STS is doing some annotation processor configuring on its own and messing with m2e-apt. That would explain why I sometimes see the generated-sources folder appear and disappear again. Has anyone encountered this before?

**Comment by Frettman** [comment]
As it turns out, it actually was STS. Their support is based on the assumption that annotations are on the classpath of the project. So while m2e-apt finds the processors in _annotationProcessorPaths_ and turns the processing on, STS says: Nope, nothing there, let's turn it off again.
Luckily, STS can be stopped from doing so in the workspace preferences:
![sts-apt](https://user-images.githubusercontent.com/24453813/28212396-8091ccba-68a1-11e7-8f52-8c0ea4caeb61.png)

**Comment by fbricon** [comment]
Closing as not an m2e-apt bug then. Please open a bug for [STS](https://github.com/spring-projects/spring-ide/issues).

cc @martinlippert @kdvolder
