### ISSUE TITLE
Update Site (even bleeding/nightly) for 1.4.0

### ISSUE THREAD

**Issue by vorburger** [jbosstools/m2e-apt#61]
@fbricon do you have, or could provide, an update site for 1.4.0? Just manual cut, or automated bleeding/nightly, either one would work for me... cauz the _[Dev builds update site](http://download.jboss.org/jbosstools/builds/staging/m2e-apt/all/repo/)_ mentioned on the README right now seems to only have a 1.3.0 from 20161026, according to Oomph's Repository Explorer.

Background: it seems that 1.3.0 doesn't work under Photon Milestone 4 (4.8.0M4) Build id: 20171214-1849 with M2E 1.8.2 from 20171007 anymore, could that be? So experienced in https://github.com/vorburger/opendaylight-eclipse-setup ... unless I'm dumb and it's some other unrelated problem; but wanted to try latest before digging further, and feeling lazy for locally building one from master... :smile:

**Comment by vorburger** [comment]
@fbricon and perhaps also @nickboldt : I have now locally built an m2e-apt from master source, and can confirm that with that it works (again) under Photon, with M2E 1.8.2 ... so, for "early adopters", it would be great if you had a chance to publish to an update site, some time.

**Comment by nickboldt** [comment]
How about this one?

http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/1.4.0-2018-01-12_16-25-02-H6/

**Comment by vorburger** [comment]
@nickboldt that works great, switched to using that in https://github.com/vorburger/opendaylight-eclipse-setup/commit/6e584b712e1045e774b446a98e74a6fcd7ad2c14, thanks a lot! (May need a more recent one later following https://github.com/jbosstools/m2e-apt/issues/62, but... later, may be.)

**Comment by nickboldt** [comment]
When/if you need a rebuild, just let me know via a github comment or nickboldt at gmail.com or nboldt at redhat.com and I'll trigger and republish a new release.
