### ISSUE TITLE
Out-of-sync composite*.xml files

### ISSUE THREAD

**Issue by nbali** [jbosstools/m2e-apt#71]
http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/compositeArtifacts.xml
http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/compositeContent.xml

They do not contain any version newer than 1.2.0-2016-01-25_16-03-44-H45, and Eclipse offers only to install the versions found there.

**Comment by fbricon** [comment]
Sorry my bad. Until I get access to fix the composite update site, you can use http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/1.5.1-2018-11-16_19-54-26-H16/ directly

**Comment by fbricon** [comment]
The composite update site has been updated.

**Comment by nbali** [comment]
No worries, I figured out the workaround myself even before I posted this :)
