### ISSUE TITLE
Everything after whitespace in processor options cut off.

### ISSUE THREAD

**Issue by Frettman** [jbosstools/m2e-apt#73]
When m2e-apt parses the processor options from the compiler arguments in the Maven project to configure the Eclipse project, everything after the first space is cut off. E.g.
**-AoptionWithSpace=beforespace afterspace**
will result in the Eclipse project having an annotation processor option of
**optionWithSpace** = **beforespace**
I tracked down the responsible code to org.jboss.tools.maven.apt.internal.utils.ProjectUtils#parseProcessorOptions(..) or more specifically to the OPTION_PATTERN. It seems to explicitly exclude space among other things, so I'm not sure what the original intention was.
Anyway, since a space isn't an issue for Maven or javac or the annotation processor API, it makes sense that m2e-apt should allow them too. As for the other excluded characters, maybe they should just be passed through, too?

**Comment by fbricon** [comment]
Does it work when surrounding the option with `"`?
Can you provide a sample project reproducing the issue?
Could you maybe provide a PR to fix this issue?

**Comment by Frettman** [comment]
I attached a simple project to demonstrate that
1. when running the Maven build, annotation processors receive the complete value.
1. the Eclipse project will only have the value up to the first space, tab, single or double quote.

[processor-options-with-space.zip](https://github.com/jbosstools/m2e-apt/files/3620235/processor-options-with-space.zip)

I could provide a PR. My solution would be to cut off the leading **-A** and split at the first **=**. Leading whitespace at the start of the option value will be preserved, trailing whitespace will be trimmed. Because, from my tests, this is how the processor options end up at the annotation processor (during a regular Maven build).
But like I said: these four characters are explicitly excluded in the regular expression. So this doesn't seem like a simple bug or oversight. So there's this nagging feeling that I might just miss something here :)

**Comment by fbricon** [comment]
Parsing is fixed:
<img width="870" alt="Screen Shot 2019-11-06 at 2 32 06 PM" src="https://user-images.githubusercontent.com/148698/68303261-c7cd2100-00a3-11ea-90a4-08d4b0fbbc45.png">

**Comment by Frettman** [comment]
Thank you! Much appreciated :)

**Comment by fbricon** [comment]
CI builds can be installed from this p2 repo: https://download.jboss.org/jbosstools/photon/snapshots/builds/m2e-apt/latest/all/repo/

**Comment by Frettman** [comment]
Can confirm that it works now. The option values in Eclipse are now just like the annotation processor receives them from Maven.
