### ISSUE TITLE
HTTP Server 'Gateway Timeout': https://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/...

### ISSUE THREAD

**Issue by yamfun** [jbosstools/m2e-apt#81]
When trying to get JBoss tool from Marketplace, got error:
HTTP Server 'Gateway Timeout': https://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/1.5.3-2019-11-08_11-04-22-H22/content.xml
HttpComponents connection error response code 504.

**Comment by jeffmaury** [comment]
Seems to be back now
